### ISSUE TITLE
quay.io is not being updated

### ISSUE THREAD

**Issue by hokichaio** [ipedrazas/drone-helm#44]
Hello @ipedrazas

I try to use the latest code in master but I think the container repository is not being updated. The latest change is 20 days ago.

https://quay.io/repository/ipedrazas/drone-helm?tab=tags

can you please confirm?

**Comment by ipedrazas** [comment]
You're absolutely right. The drone instance where I used to build this project has vanished!

**Comment by ipedrazas** [comment]
Fixed!

**Comment by hokichaio** [comment]
Thank you! :bow:

**Comment by ipedrazas** [comment]
No, thank you! otherwise, I would not have noticed... or let's put it like this, I'm sure I would have seen the problem, but I'm sure as well that as it usually happens, it would be the wrong time to fix it because I have to deliver something urgent and I have to leave to catch a plane and my mum is calling me and my phone battery dies... all at the same time.

See? you saved my day! 😄

**Comment by hokichaio** [comment]
haha😄 , I am glad that I saved your day. This is a great project and I am using it everyday! 👍
